# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/server"
  bin = "tmp/main"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  exclude_file = ["*_test.go"]
  delay = 1000
  log = "build.log"

[log]
  time = true

[serve]
  cmd = "./tmp/main"
